var color = ["red","orange","blue","green","pink","purple"];
document.write("Array is :"+color);
var startColor =color.unshift(prompt("Enter color for beginning insertion:"));
document.write("<br>Array after adding new color at the beginning:"+color);
var endColor = color.push(prompt("Enter color for end insertion:"));
document.write("<br>Array after adding new color at the end:"+color);
var color1 = color.unshift(prompt("Enter first color for beginning insertion:"));
var color2 = color.unshift(prompt("Enter second color for beginning insertion:"));
document.write("<br>Array after adding two new colors at the beginning:"+color);
color.shift();
document.write("<br>Array after deleting first color at the beginning:"+color);
color.pop();
document.write("<br>Array after deleting last color from the end: "+color);
var indexAdd = parseInt(prompt("Enter index number you want to add color:"));
var addColor = prompt("Enter color to add on the given index:");
color.splice(indexAdd,0,addColor);
document.write("<br>Array after adding color on the given index: "+color);
var indexDelete =parseInt(prompt("Enter index you want to delet the color:"));
var howMany = parseInt(prompt("Enter number that how many indexes you want to delete from the array:"));
color.splice(indexDelete,howMany);
document.write("<br>Array after removing from the desired indexes "+color);